import { Roboto } from 'next/font/google'
import Image from 'next/image'

import { Button } from '@/components/ui/button'
import { CarouselResidential } from '@/components/carousel-residential'
import { CarouselBusiness } from '@/components/carousel-business'
import { CarouselCondominiums } from '@/components/carousel-condominiums'
import Link from 'next/link'

const roboto = Roboto({
  weight: ['400', '500'],
  subsets: ['latin'],
})

export default function Home() {
  return (
    <div
      className={
        (roboto.className,
        'min-h-dvh bg-background flex flex-col items-center justify-center animate-fade-up animate-once')
      }
    >
      <div className="w-3/4 lg:h-[90dvh] mt-24 lg:mt-0 flex flex-col lg:flex-row items-center justify-center gap-12 lg:gap-0">
        <div className="lg:w-1/2 text-center lg:text-start lg:-mt-20">
          <h1 className="text-6xl font-medium">Automação</h1>
          <h2 className="text-3xl">no tempo certo</h2>
          <p className="text-md mx-auto my-6 lg:mx-0 lg:w-3/4">
            A Tecnojund oferece soluções de automação de ponta com equipamentos
            de alta qualidade, como Arduino e Microchip. Nossa experiência
            assegura integração perfeita e automação eficiente para residências
            e empresas.
          </p>
          <Link href="/chamados">
            <Button className="text-md text-white  lg:text-lg font-bold h-11 rounded-full">
              Abrir Chamado
            </Button>
          </Link>
        </div>
        <Image
          alt="house with icons of automation, Iot and smart home"
          src="/home-house.png"
          width="1081"
          height="811"
          className="sm:w-3/4 lg:w-1/2 lg:-mt-20"
          priority
          about="Generated by Leonardo.ai"
          style={{
            maxWidth: '100%',
            height: 'auto',
          }}
        ></Image>
      </div>
      <div className="w-full flex flex-col justify-center items-center">
        <h2 className="text-5xl font-medium mb-12 lg:mb-0">Serviços</h2>
        <div className="flex flex-col w-3/4 gap-20 justify-center items-center mb-24">
          <div className="w-full">
            <h3 className="text-2xl lg:text-3xl font-medium">Residencial</h3>
            <CarouselResidential />
          </div>
          <div className="w-full">
            <h3 className="text-2xl lg:text-3xl font-medium">Empresarial</h3>
            <CarouselBusiness />
          </div>
          <div className="w-full">
            <h3 className="text-2xl lg:text-3xl font-medium">Condomínios</h3>
            <CarouselCondominiums />
          </div>
        </div>
      </div>
    </div>
  )
}
